### ISSUE TITLE
Can QuireMarkZone be empty?

### ISSUE THREAD

**Issue by kat-kel** [Gallicorpora/HTR-MSS-15e-Siecle#1]
Est-ce qu'une `QuireMarkZone` devrait avoir du contenu ? Sur la feuille `bpt6k10516302_f13.xml` du document `bpt6k10516302`, le texte du `QuireMarkZone` est lié à la `MainZone` qui est mise au dessus de la zone `QuireMarkZone` ; cette dernière est donc vide. La ligne du `QuireMarkZone` est tagué comme `DefaultLine`. Contrairement au texte du `DropCapitalZone`, qui a sa propre ligne aussi, la catégorisation du texte du `QuireMarkZone` n'est pas faite qu'au niveau de la zone.

voir: `data/bpt6k10516302/bpt6k10516302_f13.xml` 
--> lignes 673-681, `ID="eSc_textblock_14f9dcb9"`, `TAGREFS="BT2496"` (`QuireMarkZone`)

**Comment by ArianePinche** [comment]
Une quireMarkZone devrait avoir du texte et ne pas être superposée dans la mesure du possible avec une mainZone. Il faut donc raccourcir la mainZone pour dégager la quireMarkZone et lui réassocier sa ligne.
